apiVersion: v1
kind: Service
metadata:
  name: warehouse
  namespace: bookstore-microservices
  labels:
    app: warehouse
spec:
  type: ClusterIP
  selector:
    app: warehouse
  ports:
  - port: 80
    targetPort: http-server
