apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-microservices-domain-warehouse
  namespace: bookstore-microservices
  labels:
    app: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      serviceAccountName: book-admin
      containers:
        - name: warehouse
          image: icyfenix/bookstore-kubernetes-domain-warehouse
          ports:
            - name: http-server
              containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y

